# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"\x1c\n\x0b\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\"h\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\r\n\x05price\x18\x06 \x01(\x01\"(\n\x08\x42ookList\x12\x1c\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\r.BookResponse\"\x07\n\x05\x45mpty2\\\n\x0e\x43\x61talogService\x12*\n\x0bGetBookInfo\x12\x0c.BookRequest\x1a\r.BookResponse\x12\x1e\n\tListBooks\x12\x06.Empty\x1a\t.BookListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKREQUEST']._serialized_start=17
  _globals['_BOOKREQUEST']._serialized_end=45
  _globals['_BOOKRESPONSE']._serialized_start=47
  _globals['_BOOKRESPONSE']._serialized_end=151
  _globals['_BOOKLIST']._serialized_start=153
  _globals['_BOOKLIST']._serialized_end=193
  _globals['_EMPTY']._serialized_start=195
  _globals['_EMPTY']._serialized_end=202
  _globals['_CATALOGSERVICE']._serialized_start=204
  _globals['_CATALOGSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
