# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catalog_pb2 as catalog__pb2


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookInfo = channel.unary_unary(
                '/CatalogService/GetBookInfo',
                request_serializer=catalog__pb2.BookRequest.SerializeToString,
                response_deserializer=catalog__pb2.BookResponse.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/CatalogService/ListBooks',
                request_serializer=catalog__pb2.Empty.SerializeToString,
                response_deserializer=catalog__pb2.BookList.FromString,
                )


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookInfo,
                    request_deserializer=catalog__pb2.BookRequest.FromString,
                    response_serializer=catalog__pb2.BookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=catalog__pb2.Empty.FromString,
                    response_serializer=catalog__pb2.BookList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CatalogService/GetBookInfo',
            catalog__pb2.BookRequest.SerializeToString,
            catalog__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CatalogService/ListBooks',
            catalog__pb2.Empty.SerializeToString,
            catalog__pb2.BookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
