# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"\'\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"C\n\x12\x43reateOrderRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1b\n\x05\x62ooks\x18\x02 \x03(\x0b\x32\x0c.orders.Book\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"*\n\x16GetOrderHistoryRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"8\n\x17GetOrderHistoryResponse\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.orders.Order\"*\n\x16GetOrderDetailsRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"h\n\x17GetOrderDetailsResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x1b\n\x05\x62ooks\x18\x03 \x03(\x0b\x32\x0c.orders.Book\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"V\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x1b\n\x05\x62ooks\x18\x03 \x03(\x0b\x32\x0c.orders.Book\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t2\xff\x01\n\rOrdersService\x12\x46\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x1b.orders.CreateOrderResponse\x12R\n\x0fGetOrderHistory\x12\x1e.orders.GetOrderHistoryRequest\x1a\x1f.orders.GetOrderHistoryResponse\x12R\n\x0fGetOrderDetails\x12\x1e.orders.GetOrderDetailsRequest\x1a\x1f.orders.GetOrderDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=24
  _globals['_BOOK']._serialized_end=63
  _globals['_CREATEORDERREQUEST']._serialized_start=65
  _globals['_CREATEORDERREQUEST']._serialized_end=132
  _globals['_CREATEORDERRESPONSE']._serialized_start=134
  _globals['_CREATEORDERRESPONSE']._serialized_end=173
  _globals['_GETORDERHISTORYREQUEST']._serialized_start=175
  _globals['_GETORDERHISTORYREQUEST']._serialized_end=217
  _globals['_GETORDERHISTORYRESPONSE']._serialized_start=219
  _globals['_GETORDERHISTORYRESPONSE']._serialized_end=275
  _globals['_GETORDERDETAILSREQUEST']._serialized_start=277
  _globals['_GETORDERDETAILSREQUEST']._serialized_end=319
  _globals['_GETORDERDETAILSRESPONSE']._serialized_start=321
  _globals['_GETORDERDETAILSRESPONSE']._serialized_end=425
  _globals['_ORDER']._serialized_start=427
  _globals['_ORDER']._serialized_end=513
  _globals['_ORDERSSERVICE']._serialized_start=516
  _globals['_ORDERSSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
