# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orders_pb2 as orders__pb2


class OrdersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/orders.OrdersService/CreateOrder',
                request_serializer=orders__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.CreateOrderResponse.FromString,
                )
        self.GetOrderHistory = channel.unary_unary(
                '/orders.OrdersService/GetOrderHistory',
                request_serializer=orders__pb2.GetOrderHistoryRequest.SerializeToString,
                response_deserializer=orders__pb2.GetOrderHistoryResponse.FromString,
                )
        self.GetOrderDetails = channel.unary_unary(
                '/orders.OrdersService/GetOrderDetails',
                request_serializer=orders__pb2.GetOrderDetailsRequest.SerializeToString,
                response_deserializer=orders__pb2.GetOrderDetailsResponse.FromString,
                )


class OrdersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=orders__pb2.CreateOrderRequest.FromString,
                    response_serializer=orders__pb2.CreateOrderResponse.SerializeToString,
            ),
            'GetOrderHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderHistory,
                    request_deserializer=orders__pb2.GetOrderHistoryRequest.FromString,
                    response_serializer=orders__pb2.GetOrderHistoryResponse.SerializeToString,
            ),
            'GetOrderDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderDetails,
                    request_deserializer=orders__pb2.GetOrderDetailsRequest.FromString,
                    response_serializer=orders__pb2.GetOrderDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrdersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrdersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrdersService/CreateOrder',
            orders__pb2.CreateOrderRequest.SerializeToString,
            orders__pb2.CreateOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrdersService/GetOrderHistory',
            orders__pb2.GetOrderHistoryRequest.SerializeToString,
            orders__pb2.GetOrderHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrdersService/GetOrderDetails',
            orders__pb2.GetOrderDetailsRequest.SerializeToString,
            orders__pb2.GetOrderDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
